# This assumes zola 0.21.1
base_url = "https://www.purpleearthhypothesis.com"
title = "Purple Earth Hypothesis"
author = "Stephen Sherratt"
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = [
    { name = "tags" },
]
generate_robots_txt = true

[markdown]
highlight_code = true
highlight_theme = "axar"
smart_punctuation = true
